import type { AttachmentDef, WeaponDef } from "./types.js";

/** Original weapon names — no trademarked titles */
export const WEAPONS: Record<string, WeaponDef> = {
  // ARs
  sparkwave: {
    id: "sparkwave",
    name: "Sparkwave",
    category: "ar",
    ammo: "556",
    damage: 22,
    headMultiplier: 2.1,
    fireRate: 10,
    magSize: 30,
    reloadTime: 2.2,
    range: 520,
    spread: 0.045,
    pelletCount: 1,
    movePenalty: 1.4,
    adsSpreadMul: 0.45,
    bulletSpeed: 920,
    slot: "primary",
  },
  ironclad: {
    id: "ironclad",
    name: "Ironclad",
    category: "ar",
    ammo: "762",
    damage: 28,
    headMultiplier: 2.2,
    fireRate: 7.5,
    magSize: 30,
    reloadTime: 2.5,
    range: 560,
    spread: 0.05,
    pelletCount: 1,
    movePenalty: 1.5,
    adsSpreadMul: 0.42,
    bulletSpeed: 880,
    slot: "primary",
  },
  // SMGs
  buzzsaw: {
    id: "buzzsaw",
    name: "Buzzsaw",
    category: "smg",
    ammo: "9mm",
    damage: 16,
    headMultiplier: 1.9,
    fireRate: 14,
    magSize: 35,
    reloadTime: 1.9,
    range: 280,
    spread: 0.07,
    pelletCount: 1,
    movePenalty: 1.1,
    adsSpreadMul: 0.55,
    bulletSpeed: 720,
    slot: "primary",
  },
  rattler: {
    id: "rattler",
    name: "Rattler",
    category: "smg",
    ammo: "45",
    damage: 19,
    headMultiplier: 1.95,
    fireRate: 11,
    magSize: 25,
    reloadTime: 2.0,
    range: 300,
    spread: 0.065,
    pelletCount: 1,
    movePenalty: 1.15,
    adsSpreadMul: 0.5,
    bulletSpeed: 700,
    slot: "primary",
  },
  // Shotgun
  thumper: {
    id: "thumper",
    name: "Thumper",
    category: "sg",
    ammo: "12g",
    damage: 18,
    headMultiplier: 1.5,
    fireRate: 1.1,
    magSize: 5,
    reloadTime: 3.2,
    range: 140,
    spread: 0.18,
    pelletCount: 8,
    movePenalty: 1.2,
    adsSpreadMul: 0.7,
    bulletSpeed: 580,
    slot: "primary",
  },
  // DMR / SR
  longreach: {
    id: "longreach",
    name: "Longreach",
    category: "dmr",
    ammo: "762",
    damage: 48,
    headMultiplier: 2.4,
    fireRate: 2.2,
    magSize: 10,
    reloadTime: 2.8,
    range: 780,
    spread: 0.02,
    pelletCount: 1,
    movePenalty: 1.8,
    adsSpreadMul: 0.25,
    bulletSpeed: 1100,
    slot: "primary",
  },
  skyline: {
    id: "skyline",
    name: "Skyline",
    category: "sr",
    ammo: "762",
    damage: 85,
    headMultiplier: 2.6,
    fireRate: 0.55,
    magSize: 5,
    reloadTime: 3.5,
    range: 1000,
    spread: 0.008,
    pelletCount: 1,
    movePenalty: 2.2,
    adsSpreadMul: 0.15,
    bulletSpeed: 1300,
    slot: "primary",
  },
  // Pistol
  sidekick: {
    id: "sidekick",
    name: "Sidekick",
    category: "pistol",
    ammo: "9mm",
    damage: 24,
    headMultiplier: 2.0,
    fireRate: 4.5,
    magSize: 15,
    reloadTime: 1.6,
    range: 260,
    spread: 0.05,
    pelletCount: 1,
    movePenalty: 1.0,
    adsSpreadMul: 0.5,
    bulletSpeed: 650,
    slot: "secondary",
  },
  // Melee
  pan: {
    id: "pan",
    name: "Pan",
    category: "melee",
    ammo: null,
    damage: 55,
    headMultiplier: 1.2,
    fireRate: 1.4,
    magSize: 0,
    reloadTime: 0,
    range: 42,
    spread: 0,
    pelletCount: 1,
    movePenalty: 1.0,
    adsSpreadMul: 1,
    bulletSpeed: 0,
    slot: "melee",
  },
  // Throwables
  frag: {
    id: "frag",
    name: "Frag",
    category: "throwable",
    ammo: null,
    damage: 100,
    headMultiplier: 1,
    fireRate: 1,
    magSize: 1,
    reloadTime: 0,
    range: 220,
    spread: 0,
    pelletCount: 1,
    movePenalty: 1,
    adsSpreadMul: 1,
    bulletSpeed: 280,
    slot: "throwable",
  },
  smoke: {
    id: "smoke",
    name: "Smoke",
    category: "throwable",
    ammo: null,
    damage: 0,
    headMultiplier: 1,
    fireRate: 1,
    magSize: 1,
    reloadTime: 0,
    range: 200,
    spread: 0,
    pelletCount: 1,
    movePenalty: 1,
    adsSpreadMul: 1,
    bulletSpeed: 260,
    slot: "throwable",
  },
};

export const ATTACHMENTS: Record<string, AttachmentDef> = {
  quick_mag: {
    id: "quick_mag",
    name: "Quick Mag",
    slot: "mag",
    compatible: ["ar", "smg", "pistol", "dmr"],
    magBonus: 10,
  },
  extended_mag: {
    id: "extended_mag",
    name: "Extended Mag",
    slot: "mag",
    compatible: ["ar", "smg", "sg", "dmr", "sr"],
    magBonus: 15,
  },
  vertical_grip: {
    id: "vertical_grip",
    name: "Vertical Grip",
    slot: "grip",
    compatible: ["ar", "smg", "dmr"],
    spreadMul: 0.85,
    recoilMul: 0.8,
  },
  compensator: {
    id: "compensator",
    name: "Compensator",
    slot: "muzzle",
    compatible: ["ar", "dmr", "sr"],
    spreadMul: 0.88,
    recoilMul: 0.75,
  },
  suppressor: {
    id: "suppressor",
    name: "Suppressor",
    slot: "muzzle",
    compatible: ["ar", "smg", "pistol", "dmr"],
    spreadMul: 0.95,
    rangeMul: 0.95,
  },
  red_dot: {
    id: "red_dot",
    name: "Red Dot",
    slot: "scope",
    compatible: ["ar", "smg", "sg", "pistol", "dmr"],
    zoom: 1.35,
  },
  dual_scope: {
    id: "dual_scope",
    name: "2x Scope",
    slot: "scope",
    compatible: ["ar", "dmr", "sr"],
    zoom: 2,
  },
  quad_scope: {
    id: "quad_scope",
    name: "4x Scope",
    slot: "scope",
    compatible: ["dmr", "sr", "ar"],
    zoom: 3.2,
  },
};

export const STARTER_WEAPON = "sidekick";
export const STARTER_MELEE = "pan";

export const WEAPON_LOOT_POOL = [
  "sparkwave",
  "ironclad",
  "buzzsaw",
  "rattler",
  "thumper",
  "longreach",
  "skyline",
  "sidekick",
];

export const ATTACHMENT_LOOT_POOL = Object.keys(ATTACHMENTS);
